### ISSUE TITLE
Get a spatial cross validation example into the exercises

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB-teaching#23]
we're relying a lot on AIC, which probably isn't great

should demonstrate cross validation

probably spatial to be faster?

**Comment by ericward-noaa** [comment]
Busy the rest of the afternoon, but I can do this tomorrow or Sun. My thoughts:
- probably put spatial example in exercise 2. Could compare spatial v non-spatial model, or spatial model with 2 sets of covariates (depth vs poly(depth)) 
- instead of 8 folds do 2, with 90/10 train/test split
- could show both ELPD (higher is better) and log-score (higher likelihood is better) or just ask them to do one of these

**Comment by seananderson** [comment]
I added an ELPD spatial piece near the beginning of ex. 2. I think it's a nice addition but ex. 2 is likely far too long now.
